In [1]:
import torch

In [22]:
testing = torch.tensor([[9., 10., 11.], [12., 13., 14.]])

In [14]:
testing.shape

torch.Size([2])

In [16]:
testing.item()

RuntimeError: a Tensor with 2 elements cannot be converted to Scalar

In [25]:
testing.mean().mean()

tensor(11.5000)

In [43]:
import torch
import pandas as pd



# Simulated batch size and number of classes
batch_size = 4
num_classes = 3  # Assume 3 possible classes
dim_rot = 6  # 6D rotation representation

# Simulated predictions (random values)
R_pred = torch.rand(batch_size, num_classes * dim_rot)  # Rotation predictions
t_pred = torch.rand(batch_size, num_classes * 3)  # Translation predictions

# Simulated class predictions (random integer class indices per sample)
cls_pred = torch.randint(0, num_classes, (batch_size,))  # Random class index per sample

print('cls_pred', cls_pred)
# Ensure integer type
cls_index = cls_pred.long()

# Compute per-sample start indices
rot_start = cls_index * dim_rot
trans_start = cls_index * 3

print('rot_start', rot_start)
print('trans_start', trans_start)

# Extract the rotation and translation using batch-wise advanced indexing
R_indexing = torch.stack([torch.arange(rot_start[i], rot_start[i] + dim_rot) for i in range(batch_size)])
t_indexing = torch.stack([torch.arange(trans_start[i], trans_start[i] + 3) for i in range(batch_size)])

print('R_indexing', R_indexing)
print('t_indexing', t_indexing)
R_extracted = R_pred[torch.arange(batch_size)[:, None], R_indexing]
t_extracted = t_pred[torch.arange(batch_size)[:, None], t_indexing]

# Print extracted matrices
print("Extracted Rotation Matrices:")
print(R_extracted.shape)
print("\nExtracted Translation Matrices:")
print(t_extracted.shape)


cls_pred tensor([2, 0, 2, 1])
rot_start tensor([12,  0, 12,  6])
trans_start tensor([6, 0, 6, 3])
R_indexing tensor([[12, 13, 14, 15, 16, 17],
        [ 0,  1,  2,  3,  4,  5],
        [12, 13, 14, 15, 16, 17],
        [ 6,  7,  8,  9, 10, 11]])
t_indexing tensor([[6, 7, 8],
        [0, 1, 2],
        [6, 7, 8],
        [3, 4, 5]])
Extracted Rotation Matrices:
torch.Size([4, 6])

Extracted Translation Matrices:
torch.Size([4, 3])


In [45]:
R_pred

tensor([[0.4717, 0.8509, 0.1280, 0.8388, 0.1803, 0.6633, 0.8244, 0.6493, 0.5884,
         0.1518, 0.4907, 0.8135, 0.5296, 0.3104, 0.8536, 0.1434, 0.9107, 0.2711],
        [0.8638, 0.3225, 0.9721, 0.4990, 0.0674, 0.0750, 0.2197, 0.6394, 0.6462,
         0.6034, 0.7747, 0.9423, 0.5737, 0.9066, 0.2224, 0.4659, 0.5855, 0.8161],
        [0.4443, 0.2776, 0.1897, 0.7521, 0.8063, 0.6408, 0.8260, 0.3800, 0.2582,
         0.9961, 0.9415, 0.4123, 0.1445, 0.5815, 0.2683, 0.2465, 0.0472, 0.9260],
        [0.3122, 0.9945, 0.6771, 0.0409, 0.0926, 0.7901, 0.7045, 0.2023, 0.9303,
         0.9630, 0.2565, 0.0662, 0.5055, 0.4021, 0.9066, 0.9510, 0.2335, 0.4566]])

In [44]:
R_extracted

tensor([[0.5296, 0.3104, 0.8536, 0.1434, 0.9107, 0.2711],
        [0.8638, 0.3225, 0.9721, 0.4990, 0.0674, 0.0750],
        [0.1445, 0.5815, 0.2683, 0.2465, 0.0472, 0.9260],
        [0.7045, 0.2023, 0.9303, 0.9630, 0.2565, 0.0662]])

In [46]:
t_extracted

tensor([[0.7618, 0.3083, 0.5601],
        [0.3799, 0.4520, 0.3295],
        [0.6412, 0.4071, 0.5284],
        [0.4910, 0.4273, 0.3910]])

In [48]:
t_pred

tensor([[0.5338, 0.8820, 0.7120, 0.1937, 0.9668, 0.5100, 0.7618, 0.3083, 0.5601],
        [0.3799, 0.4520, 0.3295, 0.8789, 0.5184, 0.3284, 0.0094, 0.0646, 0.9384],
        [0.1873, 0.1266, 0.1857, 0.9356, 0.8210, 0.0435, 0.6412, 0.4071, 0.5284],
        [0.4274, 0.7709, 0.1901, 0.4910, 0.4273, 0.3910, 0.1683, 0.7589, 0.8664]])

In [51]:
def extract_rotation_translation_matrices(cls_pred, R_pred, t_pred, dimension_rotation, dimension_translation):
    cls_index = cls_pred.long()
    batch_size = R_pred.shape[0]
    
    rot_start = cls_index * dimension_rotation
    trans_start = cls_index * dimension_translation

    R_indexing = torch.stack([torch.arange(rot_start[i], rot_start[i] + dimension_rotation) for i in range(batch_size)])
    t_indexing = torch.stack([torch.arange(trans_start[i], trans_start[i] + dimension_translation) for i in range(batch_size)])

    R_extracted = R_pred[torch.arange(batch_size)[:, None], R_indexing]
    t_extracted = t_pred[torch.arange(batch_size)[:, None], t_indexing]

    return R_extracted, t_extracted

In [52]:
extract_rotation_translation_matrices(cls_pred, R_pred, t_pred, dim_rot, 3)

(tensor([[0.5296, 0.3104, 0.8536, 0.1434, 0.9107, 0.2711],
         [0.8638, 0.3225, 0.9721, 0.4990, 0.0674, 0.0750],
         [0.1445, 0.5815, 0.2683, 0.2465, 0.0472, 0.9260],
         [0.7045, 0.2023, 0.9303, 0.9630, 0.2565, 0.0662]]),
 tensor([[0.7618, 0.3083, 0.5601],
         [0.3799, 0.4520, 0.3295],
         [0.6412, 0.4071, 0.5284],
         [0.4910, 0.4273, 0.3910]]))

In [54]:
t_extracted

tensor([[0.7618, 0.3083, 0.5601],
        [0.3799, 0.4520, 0.3295],
        [0.6412, 0.4071, 0.5284],
        [0.4910, 0.4273, 0.3910]])

In [56]:
t_extracted[[False, False, False, False]]

tensor([], size=(0, 3))